apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  namespace: oscar-svc  # Change to your namespace
type: Opaque
stringData:
  sql-alchemy-conn: "postgresql+psycopg2://airflow:airflow@airflow-postgres66-db:5432/airflow"
  # Remove Celery vars - not needed anymore
