apiVersion: v1
kind: Service
metadata:
  name: airflow-postgres66-db
  namespace: oscar-svc
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: oscar-svc-exp-airflow-postgres66